project:
  type: website
  output-dir: docs

website:
  title: "R4HTA India 2025"
  site-url: amchss.github.io/r4hta_india/
  navbar:
    background: primary  
    foreground: light
    search: true
    left:
      - href: index.qmd
        text: "Home"
        icon: house
      - href: day_one.qmd
        text: "Day One"
        icon: calendar-day
      - href: day_two.qmd
        text: "Day Two"
        icon: calendar-day
      - href: data_dwnld.qmd
        text: "Data"
        icon: database
      - href: about.qmd
        text: "About Us"
        icon: people
      - href: gallery.qmd
        text: "Gallery"
        icon: images
    right:
      - icon: envelope
        href: mailto:hta.sctimst@gmail.com
      - icon: github
        href: https://github.com/amchss/r4hta_india

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    smooth-scroll: true
    page-navigation: true
    highlight-style: tango
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

execute:
  freeze: auto
